TARGET = iphone:clang:9.3:9.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FrontFlashiOS9
FrontFlashiOS9_FILES = Tweak.xm
FrontFlashiOS9_EXTRA_FRAMEWORKS = CydiaSubstrate
FrontFlashiOS9_INSTALL_PATH = /Library/MobileSubstrate/DynamicLibraries/FrontFlash

include $(THEOS_MAKE_PATH)/library.mk
