GO_EASY_ON_ME = 1
SDKVERSION = 7.0
ARCHS = armv7 arm64

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FrontFlashiPadiOS7
FrontFlashiPadiOS7_FILES = Tweak.xm
FrontFlashiPadiOS7_LIBRARIES = substrate
FrontFlashiPadiOS7_INSTALL_PATH = /Library/Application Support/FrontFlash

include $(THEOS_MAKE_PATH)/library.mk
