GO_EASY_ON_ME = 1
SDKVERSION = 7.0
ARCHS = armv7 arm64

include ../theos/makefiles/common.mk

TWEAK_NAME = FrontFlashiPadiOS7
FrontFlashiPadiOS7_FILES = Tweak.xm
FrontFlashiPadiOS7_INSTALL_PATH = /Library/Application Support/FrontFlash

include $(THEOS_MAKE_PATH)/tweak.mk
