GO_EASY_ON_ME = 1
SDKVERSION = 6.0
ARCHS = armv7

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FrontFlashiOS456
FrontFlashiOS456_FILES = Tweak.xm
FrontFlashiOS456_FRAMEWORKS = QuartzCore UIKit
FrontFlashiOS456_LIBRARIES = substrate
FrontFlashiOS456_INSTALL_PATH = /Library/Application Support/FrontFlash

include $(THEOS_MAKE_PATH)/library.mk
