GO_EASY_ON_ME = 1
SDKVERSION = 6.0
ARCHS = armv7

include ../theos/makefiles/common.mk

TWEAK_NAME = FrontFlashiOS456
FrontFlashiOS456_FILES = Tweak.xm
FrontFlashiOS456_FRAMEWORKS = QuartzCore UIKit
FrontFlashiOS456_INSTALL_PATH = /Library/Application Support/FrontFlash

include $(THEOS_MAKE_PATH)/tweak.mk
