GO_EASY_ON_ME = 1
TARGET = iphone:latest:8.0
ARCHS = armv7 arm64

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FrontFlashiPadiOS8
FrontFlashiPadiOS8_FILES = Tweak.xm
FrontFlashiPadiOS8_LIBRARIES = substrate
FrontFlashiPadiOS8_INSTALL_PATH = /Library/Application Support/FrontFlash

include $(THEOS_MAKE_PATH)/library.mk
