GO_EASY_ON_ME = 1
SDKVERSION = 7.0
ARCHS = armv7 arm64

include ../theos/makefiles/common.mk

TWEAK_NAME = FrontFlashiPadiOS8
FrontFlashiPadiOS8_FILES = Tweak.xm
FrontFlashiPadiOS8_INSTALL_PATH = /Library/Application Support/FrontFlash

include $(THEOS_MAKE_PATH)/tweak.mk
