GO_EASY_ON_ME = 1
SDKVERSION = 7.0
ARCHS = armv7 arm64

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FrontFlashiOS7
FrontFlashiOS7_FILES = Tweak.xm
FrontFlashiOS7_FRAMEWORKS = UIKit
FrontFlashiOS7_PRIVATE_FRAMEWORKS = GraphicsServices
FrontFlashiOS7_LIBRARIES = substrate
FrontFlashiOS7_INSTALL_PATH = /Library/Application Support/FrontFlash

include $(THEOS_MAKE_PATH)/library.mk
