TARGET = iphone:clang:7.1:7.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FrontFlashiOS7
FrontFlashiOS7_FILES = Tweak.xm
FrontFlashiOS7_FRAMEWORKS = UIKit
FrontFlashiOS7_PRIVATE_FRAMEWORKS = GraphicsServices
FrontFlashiOS7_EXTRA_FRAMEWORKS = CydiaSubstrate
FrontFlashiOS7_INSTALL_PATH = /Library/MobileSubstrate/DynamicLibraries/FrontFlash

include $(THEOS_MAKE_PATH)/library.mk
