TARGET = iphone:clang:latest:9.0

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FrontFlashiOS10
FrontFlashiOS10_FILES = Tweak.xm
FrontFlashiOS10_EXTRA_FRAMEWORKS = CydiaSubstrate
FrontFlashiOS10_INSTALL_PATH = /Library/Application Support/FrontFlash

include $(THEOS_MAKE_PATH)/library.mk
