GO_EASY_ON_ME = 1
SDKVERSION = 6.0
ARCHS = armv7

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FrontFlashiOS56
FrontFlashiOS56_FILES = Tweak.xm
FrontFlashiOS56_FRAMEWORKS = UIKit
FrontFlashiOS56_LIBRARIES = substrate
FrontFlashiOS56_INSTALL_PATH = /Library/Application Support/FrontFlash

include $(THEOS_MAKE_PATH)/library.mk
