GO_EASY_ON_ME = 1
TARGET = iphone:latest
ARCHS = armv7

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = Workaround_Cephei_iOS56
Workaround_Cephei_iOS56_FILES = Tweak.m
Workaround_Cephei_iOS56_FRAMEWORKS = UIKit
Workaround_Cephei_iOS56_LIBRARIES = cepheiprefs
Workaround_Cephei_iOS56_INSTALL_PATH = /Library/Application Support/FrontFlash

include $(THEOS_MAKE_PATH)/library.mk
