GO_EASY_ON_ME = 1
SDKVERSION = 8.0
ARCHS = armv7 arm64

include ../theos/makefiles/common.mk

TWEAK_NAME = FrontFlashiOS8
FrontFlashiOS8_FILES = Tweak.xm
FrontFlashiOS8_FRAMEWORKS = UIKit
FrontFlashiOS8_PRIVATE_FRAMEWORKS = GraphicsServices
FrontFlashiOS8_INSTALL_PATH = /Library/Application Support/FrontFlash

include $(THEOS_MAKE_PATH)/tweak.mk
