GO_EASY_ON_ME = 1
ARCHS = armv7 arm64

include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = FrontFlashiPadiOS9
FrontFlashiPadiOS9_FILES = Tweak.xm
FrontFlashiPadiOS9_LIBRARIES = substrate
FrontFlashiPadiOS9_INSTALL_PATH = /Library/Application Support/FrontFlash

include $(THEOS_MAKE_PATH)/library.mk
